In [1]:
# https://github.com/huggingface/lerobot/blob/main/examples/7_get_started_with_real_robot.md

In [1]:
## CHANGE THIS
# run `ls /dev | grep ttyACM` to find the port
# flatpak run com.obsproject.Studio then `v4l2-ctl --list-devices` to find the camera index

follower_port = "/dev/ttyACM2"
leader_port = "/dev/ttyACM3"
camera_index = 4 # flatpak run obs studio. 

In [2]:
import os
import sys
parent_of_parent = os.path.dirname(os.path.dirname(os.getcwd()))
sys.path.append(parent_of_parent)

In [3]:
from lerobot.common.robot_devices.robots.configs import KochRobotConfig
from lerobot.common.robot_devices.robots.manipulator import ManipulatorRobot

from lerobot.common.robot_devices.motors.configs import DynamixelMotorsBusConfig
from lerobot.common.robot_devices.motors.dynamixel import DynamixelMotorsBus

from lerobot.common.robot_devices.cameras.configs import OpenCVCameraConfig
from lerobot.common.robot_devices.cameras.opencv import OpenCVCamera

In [4]:

leader_config = DynamixelMotorsBusConfig(
    port=leader_port,
    motors={
        # name: (index, model)
        "shoulder_pan": (1, "xl330-m077"),
        "shoulder_lift": (2, "xl330-m077"),
        "elbow_flex": (3, "xl330-m077"),
        "wrist_flex": (4, "xl330-m077"),
        "wrist_roll": (5, "xl330-m077"),
        "gripper": (6, "xl330-m077"),
    },
)

follower_config = DynamixelMotorsBusConfig(
    port=follower_port,
    motors={
        # name: (index, model)
        "shoulder_pan": (1, "xl430-w250"),
        "shoulder_lift": (2, "xl430-w250"),
        "elbow_flex": (3, "xl330-m288"),
        "wrist_flex": (4, "xl330-m288"),
        "wrist_roll": (5, "xl330-m288"),
        "gripper": (6, "xl330-m288"),
    },
)

leader_arm = DynamixelMotorsBus(leader_config)
follower_arm = DynamixelMotorsBus(follower_config)

In [24]:
robot_config = KochRobotConfig(
    leader_arms={"main": leader_config},
    follower_arms={"main": follower_config},
    calibration_dir=".cache/calibration/koch",
    cameras={
        # "laptop": OpenCVCameraConfig(0, fps=30, width=640, height=480),
        "phone": OpenCVCameraConfig(camera_index=camera_index, fps=30, width=640, height=480),
    },
    # cameras={},
)
robot = ManipulatorRobot(robot_config)
robot.connect()

Connecting main follower arm.
Connecting main leader arm.
Activating torque on main follower arm.


[ WARN:0@1947.942] global cap_gstreamer.cpp:2839 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module typefind reported: Could not determine type of stream.
[ WARN:0@1947.942] global cap_gstreamer.cpp:1698 open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@1947.942] global cap_gstreamer.cpp:1173 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0@1949.109] global cap_gstreamer.cpp:2839 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module typefind reported: Could not determine type of stream.
[ WARN:0@1949.109] global cap_gstreamer.cpp:1698 open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@1949.109] global cap_gstreamer.cpp:1173 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created


In [6]:
observation, action = robot.teleop_step(record_data=True)
# print(observation["observation.images.laptop"].shape)
print(observation["observation.images.phone"].shape)
print(observation["observation.images.phone"].min().item())
print(observation["observation.images.phone"].max().item())


torch.Size([480, 640, 3])
0
255


In [7]:
# turn torque mode off before disconnecting
robot.follower_arms["main"].write("Torque_Enable", 0)
robot.disconnect()

In [8]:
robot.connect()

Connecting main follower arm.
Connecting main leader arm.
Activating torque on main follower arm.
Wrong motor position range detected for elbow_flex. Expected to be in nominal range of [-180, 180] degrees (a full rotation), with a maximum range of [-270, 270] degrees to account for joints that can rotate a bit more, but present value is 503.4375 degree. This might be due to a cable connection issue creating an artificial 360 degrees jump in motor values. You need to recalibrate by running: `python lerobot/scripts/control_robot.py calibrate`


[ WARN:0@67.526] global cap_gstreamer.cpp:2839 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module typefind reported: Could not determine type of stream.
[ WARN:0@67.527] global cap_gstreamer.cpp:1698 open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@67.527] global cap_gstreamer.cpp:1173 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0@68.759] global cap_gstreamer.cpp:2839 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module typefind reported: Could not determine type of stream.
[ WARN:0@68.759] global cap_gstreamer.cpp:1698 open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@68.759] global cap_gstreamer.cpp:1173 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created


record data and replay

In [19]:
### MAIN CODE FOR RECORDING DATA ###
import time
from lerobot.scripts.control_robot import busy_wait

record_time_s = 10
fps = 60

states = []
actions = []
frames = []
for _ in range(record_time_s * fps):
    start_time = time.perf_counter()
    observation, action = robot.teleop_step(record_data=True)

    # frames.append(observation["observation.images.phone"])
    states.append(observation["observation.state"])
    actions.append(action["action"])

    dt_s = time.perf_counter() - start_time
    busy_wait(1 / fps - dt_s)

# Note that observation and action are available in RAM, but
# you could potentially store them on disk with pickle/hdf5 or
# our optimized format `LeRobotDataset`. More on this next.

In [20]:
observation["observation.images.phone"].shape

torch.Size([480, 640, 3])

In [21]:
actions

[tensor([ 67.8516,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.8145, 125.3320,  40.9570, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.9395,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.9395,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.8145, 125.3320,  40.9570, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.9023, 125.3320,  40.8691, 187.3828,  35.5078]),
 tensor([ 67.8516,  84.8145, 125.3320,  40.8691, 187.3828,  35.5078]),
 tenso

In [27]:
# target position for follower arm
import numpy as np
target = np.array([ 69.1699,  83.4082, 122.9590,  47.8125, 184.7461,  -7.0312])
robot.follower_arms["main"].write("Goal_Position", target)

In [65]:
# save actions and replay
import pickle

with open(".cache/actions.pkl", "wb") as f:
  pickle.dump(actions, f)


In [66]:
with open(".cache/actions.pkl", "rb") as f:
  actions = pickle.load(f)


In [76]:
speed = 2
for i in range(len(actions)):
    start_time = time.perf_counter()
    
    robot.follower_arms["main"].write("Goal_Position", actions[i])
    # robot.leader_arms["main"].write("Goal_Position", actions[i])

    dt_s = time.perf_counter() - start_time
    busy_wait(1/speed * 1 / fps - dt_s)

In [23]:
robot.disconnect()

In [70]:
robot.connect()

RobotDeviceAlreadyConnectedError: ManipulatorRobot is already connected. Do not run `robot.connect()` twice.

calib

In [39]:
# calibration complete! check if match
leader_pos = robot.leader_arms["main"].read("Present_Position")
follower_pos = robot.follower_arms["main"].read("Present_Position")

print(leader_pos)
print(follower_pos)

[  49.21875   133.24219    95.53711    18.544922 -261.21094    35.06836 ]
[  6.9433594  70.927734  151.52344   -74.9707     90.08789    51.416016 ]


[ WARN:0@10958.301] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@10968.312] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@10978.322] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.


In [32]:
# teleop for 30s
import tqdm
seconds = 30
frequency = 200 # 200 Hz
for _ in tqdm.tqdm(range(seconds*frequency)):
    leader_pos = robot.leader_arms["main"].read("Present_Position")
    robot.follower_arms["main"].write("Goal_Position", leader_pos)

100%|██████████| 6000/6000 [00:31<00:00, 192.09it/s]


[ WARN:0@3219.956] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.


In [33]:
# same but simpler code version
seconds = 300
for _ in tqdm.tqdm(range(seconds*frequency)):
    robot.teleop_step()

100%|██████████| 60000/60000 [05:15<00:00, 190.13it/s]


[ WARN:0@3550.293] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3560.302] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3570.313] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3580.323] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3590.333] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3600.344] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3610.352] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3620.363] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3630.374] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3640.384] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3650.392] global cap_

In [20]:
leader_pos = robot.leader_arms["main"].read("Present_Position")
follower_pos = robot.follower_arms["main"].read("Present_Position")
# observation = follower arm original pos, action = leader arm pos
observation, action = robot.teleop_step(record_data=True)

print(follower_pos)
print(observation)
print(leader_pos)
print(action)

[-21.796875 125.771484 167.69531   20.126953  76.02539   34.277344]
{'observation.state': tensor([-21.7969, 125.7715, 167.6953,  20.1270,  76.0254,  34.2773])}
[-15.1171875 133.50586   162.59766    31.113281   73.47656    34.716797 ]
{'action': tensor([-15.1172, 133.5059, 162.5977,  31.1133,  73.4766,  34.7168])}


In [6]:
robot.disconnect()

check camera

`v4l2-ctl --list-devices`

`v4l2-ctl -d /dev/video4 --get-fmt-video`

In [30]:
# check camera index corresponding to OBS
# python lerobot/common/robot_devices/cameras/opencv.py --images-dir outputs/images_from_opencv_cameras
camera_config = OpenCVCameraConfig(camera_index=4)
camera = OpenCVCamera(camera_config)
camera.connect()

Linux detected. Finding available camera indices through scanning '/dev/video*' ports


[ WARN:0@1070.469] global cap_gstreamer.cpp:2839 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module typefind reported: Could not determine type of stream.
[ WARN:0@1070.470] global cap_gstreamer.cpp:1698 open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@1070.470] global cap_gstreamer.cpp:1173 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0@1070.583] global cap_gstreamer.cpp:2839 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0@1070.583] global cap_gstreamer.cpp:1698 open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@1070.583] global cap_gstreamer.cpp:1173 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0@1070.619] global cap_gstreamer.cpp:2839 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Cou

Camera found at index /dev/video0
Camera found at index /dev/video2


[ WARN:0@1070.725] global cap_gstreamer.cpp:2839 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0@1070.725] global cap_gstreamer.cpp:1698 open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@1070.725] global cap_gstreamer.cpp:1173 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0@1071.870] global cap_gstreamer.cpp:2839 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module typefind reported: Could not determine type of stream.
[ WARN:0@1071.870] global cap_gstreamer.cpp:1698 open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@1071.870] global cap_gstreamer.cpp:1173 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created


ValueError: `camera_index` is expected to be one of these available cameras [0, 2], but 4 is provided instead. To find the camera index you should use, run `python lerobot/common/robot_devices/cameras/opencv.py`.

In [6]:
color_image = camera.read()

print(color_image.shape)
print(color_image.dtype)

(480, 640, 3)
uint8


In [14]:
# MAKE SURE TO RUN THIS BEFORE TRYING TO ASSIGN IN CONFIG
camera.disconnect()

NameError: name 'camera' is not defined