In [1]:
# https://github.com/huggingface/lerobot/blob/main/examples/7_get_started_with_real_robot.md

In [1]:
import os
import sys
parent_of_parent = os.path.dirname(os.path.dirname(os.getcwd()))
sys.path.append(parent_of_parent)

In [17]:
from lerobot.common.robot_devices.robots.configs import KochRobotConfig
from lerobot.common.robot_devices.robots.manipulator import ManipulatorRobot

from lerobot.common.robot_devices.motors.configs import DynamixelMotorsBusConfig
from lerobot.common.robot_devices.motors.dynamixel import DynamixelMotorsBus

from lerobot.common.robot_devices.cameras.configs import OpenCVCameraConfig
from lerobot.common.robot_devices.cameras.opencv import OpenCVCamera

[ WARN:0@4674.275] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@4684.285] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@4694.295] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@4704.305] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@4714.315] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@4724.325] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@4734.335] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@4744.345] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@4754.355] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@4764.365] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@4774.375] global cap_

In [2]:
follower_port = "/dev/ttyACM3"
leader_port = "/dev/ttyACM4"

leader_config = DynamixelMotorsBusConfig(
    port=leader_port,
    motors={
        # name: (index, model)
        "shoulder_pan": (1, "xl330-m077"),
        "shoulder_lift": (2, "xl330-m077"),
        "elbow_flex": (3, "xl330-m077"),
        "wrist_flex": (4, "xl330-m077"),
        "wrist_roll": (5, "xl330-m077"),
        "gripper": (6, "xl330-m077"),
    },
)

follower_config = DynamixelMotorsBusConfig(
    port=follower_port,
    motors={
        # name: (index, model)
        "shoulder_pan": (1, "xl430-w250"),
        "shoulder_lift": (2, "xl430-w250"),
        "elbow_flex": (3, "xl330-m288"),
        "wrist_flex": (4, "xl330-m288"),
        "wrist_roll": (5, "xl330-m288"),
        "gripper": (6, "xl330-m288"),
    },
)

leader_arm = DynamixelMotorsBus(leader_config)
follower_arm = DynamixelMotorsBus(follower_config)

In [18]:
robot_config = KochRobotConfig(
    leader_arms={"main": leader_config},
    follower_arms={"main": follower_config},
    calibration_dir=".cache/calibration/koch",
    cameras={
        # "laptop": OpenCVCameraConfig(0, fps=30, width=640, height=480),
        "phone": OpenCVCameraConfig(4, fps=30, width=640, height=480),
    },
    # cameras={},
)
robot = ManipulatorRobot(robot_config)
robot.connect()

Connecting main follower arm.

Try running `python lerobot/scripts/find_motors_bus_port.py` to make sure you are using the correct port.



[ WARN:0@4854.455] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/lerobot/lib/python3.11/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ellen/code/*/lerobot/lerobot/common/robot_devices/motors/dynamixel.py", line 329, in connect
    if not self.port_handler.openPort():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/lerobot/lib/python3.11/site-packages/dynamixel_sdk/port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/lerobot/

SerialException: [Errno 2] could not open port /dev/ttyACM3: [Errno 2] No such file or directory: '/dev/ttyACM3'

In [9]:
observation, action = robot.teleop_step(record_data=True)
# print(observation["observation.images.laptop"].shape)
print(observation["observation.images.phone"].shape)
print(observation["observation.images.phone"].min().item())
print(observation["observation.images.phone"].max().item())


torch.Size([480, 640, 3])
0
17


Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error reading in thread: Can't capture color image from camera 4.
Error read

In [19]:
robot.disconnect()

In [21]:
robot.connect()

Connecting main follower arm.
Connecting main leader arm.
Activating torque on main follower arm.


record data and replay

In [10]:
### MAIN CODE FOR RECORDING DATA ###
import time
from lerobot.scripts.control_robot import busy_wait

record_time_s = 30
fps = 60

states = []
actions = []
frames = []
for _ in range(record_time_s * fps):
    start_time = time.perf_counter()
    observation, action = robot.teleop_step(record_data=True)

    frames.append(observation["observation.images.phone"])
    states.append(observation["observation.state"])
    actions.append(action["action"])

    dt_s = time.perf_counter() - start_time
    busy_wait(1 / fps - dt_s)

# Note that observation and action are available in RAM, but
# you could potentially store them on disk with pickle/hdf5 or
# our optimized format `LeRobotDataset`. More on this next.

/opt/miniconda3/envs/lerobot/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [14]:
observation["observation.images.phone"].shape

torch.Size([480, 640, 3])

In [42]:
actions

[tensor([  42.6270,  133.6816,   98.1738,   -4.0430, -259.7168,   34.6289]),
 tensor([  42.6270,  133.6816,   98.1738,   -4.0430, -259.7168,   34.7168]),
 tensor([  42.6270,  133.6816,   98.1738,   -4.0430, -259.7168,   34.7168]),
 tensor([  42.6270,  133.6816,   98.1738,   -4.0430, -259.6289,   34.7168]),
 tensor([  42.7148,  133.6816,   98.1738,   -4.0430, -259.6289,   34.8047]),
 tensor([  42.6270,  133.6816,   98.1738,   -4.0430, -259.6289,   34.7168]),
 tensor([  42.6270,  133.6816,   98.1738,   -4.0430, -259.6289,   34.7168]),
 tensor([  42.6270,  133.6816,   98.1738,   -4.0430, -259.6289,   34.7168]),
 tensor([  42.6270,  133.6816,   98.1738,   -4.0430, -259.6289,   34.7168]),
 tensor([  42.6270,  133.6816,   98.1738,   -4.0430, -259.6289,   34.8047]),
 tensor([  42.7148,  133.6816,   98.1738,   -4.0430, -259.6289,   34.8047]),
 tensor([  42.7148,  133.6816,   98.1738,   -4.0430, -259.6289,   34.8047]),
 tensor([  42.7148,  133.6816,   98.1738,   -4.0430, -259.6289,   34.8047]),

In [65]:
# save actions and replay
import pickle

with open("actions.pkl", "wb") as f:
  pickle.dump(actions, f)


In [66]:
with open("actions.pkl", "rb") as f:
  actions = pickle.load(f)


In [76]:
speed = 2
for i in range(len(actions)):
    start_time = time.perf_counter()
    
    robot.follower_arms["main"].write("Goal_Position", actions[i])
    # robot.leader_arms["main"].write("Goal_Position", actions[i])

    dt_s = time.perf_counter() - start_time
    busy_wait(1/speed * 1 / fps - dt_s)

In [54]:
robot.disconnect()

In [70]:
robot.connect()

RobotDeviceAlreadyConnectedError: ManipulatorRobot is already connected. Do not run `robot.connect()` twice.

calib

In [39]:
# calibration complete! check if match
leader_pos = robot.leader_arms["main"].read("Present_Position")
follower_pos = robot.follower_arms["main"].read("Present_Position")

print(leader_pos)
print(follower_pos)

[  49.21875   133.24219    95.53711    18.544922 -261.21094    35.06836 ]
[  6.9433594  70.927734  151.52344   -74.9707     90.08789    51.416016 ]


[ WARN:0@10958.301] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@10968.312] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@10978.322] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.


In [32]:
# teleop for 30s
import tqdm
seconds = 30
frequency = 200 # 200 Hz
for _ in tqdm.tqdm(range(seconds*frequency)):
    leader_pos = robot.leader_arms["main"].read("Present_Position")
    robot.follower_arms["main"].write("Goal_Position", leader_pos)

100%|██████████| 6000/6000 [00:31<00:00, 192.09it/s]


[ WARN:0@3219.956] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.


In [33]:
# same but simpler code version
seconds = 300
for _ in tqdm.tqdm(range(seconds*frequency)):
    robot.teleop_step()

100%|██████████| 60000/60000 [05:15<00:00, 190.13it/s]


[ WARN:0@3550.293] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3560.302] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3570.313] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3580.323] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3590.333] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3600.344] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3610.352] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3620.363] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3630.374] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3640.384] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
[ WARN:0@3650.392] global cap_

In [20]:
leader_pos = robot.leader_arms["main"].read("Present_Position")
follower_pos = robot.follower_arms["main"].read("Present_Position")
# observation = follower arm original pos, action = leader arm pos
observation, action = robot.teleop_step(record_data=True)

print(follower_pos)
print(observation)
print(leader_pos)
print(action)

[-21.796875 125.771484 167.69531   20.126953  76.02539   34.277344]
{'observation.state': tensor([-21.7969, 125.7715, 167.6953,  20.1270,  76.0254,  34.2773])}
[-15.1171875 133.50586   162.59766    31.113281   73.47656    34.716797 ]
{'action': tensor([-15.1172, 133.5059, 162.5977,  31.1133,  73.4766,  34.7168])}


In [6]:
robot.disconnect()

check camera

`v4l2-ctl --list-devices`

`v4l2-ctl -d /dev/video4 --get-fmt-video`

In [5]:
# check camera index corresponding to OBS
# python lerobot/common/robot_devices/cameras/opencv.py --images-dir outputs/images_from_opencv_cameras
camera_config = OpenCVCameraConfig(camera_index=4)
camera = OpenCVCamera(camera_config)
camera.connect()

In [6]:
color_image = camera.read()

print(color_image.shape)
print(color_image.dtype)

(480, 640, 3)
uint8


In [7]:
# MAKE SURE TO RUN THIS BEFORE TRYING TO ASSIGN IN CONFIG
camera.disconnect()